
# application.properties

spring.application.name=MySpringBoot4Project

server.port=8081

# Docker 컨테이너 등 외부 요청 접속 허용 설정 추가
server.address=0.0.0.0

# MariaDB
spring.datasource.url=jdbc:mariadb://172.17.128.1:3306/lab_db
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.username=lab
spring.datasource.password=lab


# JPA update
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

